version: "3.8"
services:
  pwa:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - HOST=0.0.0.0
    restart: always
    command: npm run dev
    ports:
      - "8080:8080"
    volumes: 
      - ./:/app
      - node_modules:/app/node_modules/
volumes:
  node_modules: